#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Kriechen\Command\KriechenCommand;

$application = new Application();
$application->add(new KriechenCommand());

$application->run();
